language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn test:coverage
  - yarn build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    keep_history: true
    on:
      branch: $BRANCH_NAME
  - provider: heroku
    api_key:
      secure: $HEROKU_TOKEN
    app: react-ci-amy
    on:
      repo: yamresh/react-ci
addons:
  sonarcloud:
    organization: "yamresh" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
script:
    # other script steps might be done before running the actual analysis
  - sonar-scanner

notifications:
  email:
    - amreshy29@gmail.com
    - testindia12@yopmail.com
