language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn test:coverage
  - yarn build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    keep_history: true
    on:
      branch: $BRANCH_NAME

#addons:
#  sonarcloud:
#    organization: "yamresh"
#    token:
#      secure: "b8386c4920e9b1a7feadc11b1d82d2b34c5fd5d5" # encrypted value of your token
#script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - sonar-scanner
notifications:
  email:
    - amreshy29@gmail.com
