language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run test:coverage
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "5348f22f404f504d82b66ce45604d8432f59f931"
  local_dir: build
  keep_history: true
  on:
    branch: master
